name: Run HTML5 App with Selenium

on: [push]

jobs:
  run-tests:
    runs-on: ubuntu-latest

    services:
      web:
        image: node:14
        ports:
          - 8080:8080
        options: >-
          --health-cmd "curl --fail http://localhost:8080 || exit 1"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 3

    steps:
    - name: Check out repository
      uses: actions/checkout@v4
      with:
        repository: john4650-hub/PingPong-with-phaser3
        token: ${{ secrets.TK }}
        ref: main

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'

    - name: Install dependencies
      run: |
        npm install http-server

    - name: Start web server
      run: |
        npx http-server -p 8080 &
        sleep 5

    - name: Install Python dependencies
      run: |
        pip install selenium

    - name: Run Selenium tests
      run: |
        python run_selenium.py
        chmod +x run_command.sh
        ./run_command.sh 0.${{ github.run_number }}.0
      env:
        GITHUB_TOKEN: ${{ secrets.TK }}

